version: '3.8'

services:
  expo:
    build: .
    container_name: expo_app
    volumes:
      - .:/app
      - /app/node_modules 
    ports:
      - "19000:19000"  # Expo development server
      - "19001:19001"  # Expo web interface
      - "19002:19002"  # Expo debugger
