services:
  app:
    image: expo-cli
    container_name: expo_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "19000:19000"  # Expo development server
      - "19001:19001"  # Expo web interface
      - "19002:19002"  # Expo debugger
    command: >
      sh -c "npm install && expo start --tunnel"