# name: Build & Deploy
# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Deploy API PROD
#         uses: appleboy/ssh-action@v1.0.3
#         with:
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.USERNAME }}
#           key: ${{ secrets.SSHKEY }}
#           script: |
#             cd /home/ajalife/mender-front
#             git pull origin main
#             docker compose down expo
#             docker compose up -d expo